# Generated by Django 4.2.7 on 2026-03-30 00:46

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=15, validators=[store.models.validar_telefono], verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección de envío')),
                ('ciudad', models.CharField(default='Santa Cruz', max_length=100, verbose_name='Ciudad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('editorial', models.CharField(default='Desconocida', max_length=100, verbose_name='Editorial')),
                ('genero', models.CharField(choices=[('shonen', 'Shōnen'), ('shojo', 'Shōjo'), ('seinen', 'Seinen'), ('josei', 'Josei'), ('isekai', 'Isekai'), ('mecha', 'Mecha'), ('deportes', 'Deportes'), ('terror', 'Terror'), ('comedia', 'Comedia'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Género')),
                ('volumen', models.PositiveIntegerField(default=1, verbose_name='Número de volumen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[store.models.validar_precio_positivo], verbose_name='Precio (Bs)')),
                ('stock', models.IntegerField(default=0, validators=[store.models.validar_stock_no_negativo], verbose_name='Stock disponible')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en tienda')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Mangas',
                'ordering': ['titulo', 'volumen'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado del pedido')),
                ('direccion_envio', models.TextField(blank=True, verbose_name='Dirección de envío')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='store.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario (al momento del pedido)')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='store.manga', verbose_name='Manga')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
            },
        ),
    ]
